import {Injectable} from '@angular/core';
import {Observable} from 'rxjs/Rx';
import {Job} from './job';


const jobs: Array<any> = [{
  'createdBy': 'admin',
  'createdDate': '2017-06-26T06:59:08.209Z',
  'lastModifiedBy': 'admin',
  'lastModifiedDate': '2017-06-26T06:59:08.209Z',
  'id': '9dd31ca9-b4b6-4543-8612-be0479a5955f',
  'externalId': '00000609083',
  'publicationStartDate': '2017-06-22',
  'publicationEndDate': '2020-06-22',
  'externalUrl': 'http://www.externer-stellenvermittler.ch/talent',
  'applicationUrl': null,
  'registrationDate': '2017-06-22',
  'cancellationDate': null,
  'cancellationReason': null,
  'title': 'Software-Entwickler',
  'description': '- 2 Software-Entwickler\n- Stellenantritt per sofort, unbefristet, 100%\n- Aufgaben: Spannende Entwicklungsprojekte realisieren, Weiterentwicklung von Projekten, Durchführung von\nanspruchsvollen Kundenprojekten, Aufgaben im gesamten Entwicklungsprozess\n- Anforderungen: Hochschulabschluss (FH, ETH, Uni) in Informatik, Erfahrung im Bereich Java, Ruby on Rails\noder Python, kennen moderne Entwicklungsprozesse, belastbar, engagiert, kreativ',
  'workingTimePercentageMin': 100,
  'workingTimePercentageMax': 100,
  'startDate': '2017-06-22',
  'endDate': '2017-06-22',
  'startsImmediately': true,
  'permanent': true,
  'fingerPrint': 'b863e2e50f0908a01bfac745bdc9731aee2a5c7367f57d450ceed26750395ab6721503afef3b0b50',
  'numberOfJobs': 1,
  'jobSharing': null,
  'suitableForDisabled': false,
  'locality': {
    'text': 'Chur',
    'zipCode': '7000',
    'communalCode': '3901',
    'cantonCode': 'GR',
    'regionCode': 'GR01',
    'countryCode': 'CH'
  },
  'paymentMin': null,
  'paymentMax': null,
  'currencyCode': 'CHF',
  'ageMin': 25,
  'ageMax': 50,
  'ageRestrictionReason': null,
  'gender': 'FEMALE',
  'hasPersonalVehicle': false,
  'drivingLicenseLevel': null,
  'companyName': 'Max Power IT',
  'companyAddressLine1': 'Putzstrasse 3',
  'companyAddressLine2': null,
  'companyZipCode': '7000',
  'companyCity': 'Chur',
  'companyCountryCode': 'CH',
  'companyPostboxNumber': null,
  'companyPostboxZipCode': null,
  'companyPostboxCity': null,
  'companyPhone': null,
  'companyEmail': 'xxxx@xxxxxxx.ch',
  'companyWebsite': null,
  'contactTitle': 'Herr',
  'contactFirstName': 'Hans',
  'contactLastName': 'Meiser',
  'contactPhone': '079 999 99 99',
  'contactEmail': 'xxxx@xxxxxxx.ch',
  'professions': [{
    'code': '69259',
    'qualificationLevel': null,
    'relation': null,
    'experienceInYears': 1,
    'educationLevel': null
  }],
  'languages': [{
    'code': 'DE',
    'spokenLevel': 'GOOD',
    'writtenLevel': 'VERY_GOOD',
    'isMothertongue': true,
    'isLanguageStayRequired': true
  }]
}, {
  'createdBy': 'system',
  'createdDate': '2017-06-26T06:11:25.932Z',
  'lastModifiedBy': 'system',
  'lastModifiedDate': '2017-06-26T06:11:25.932Z',
  'id': 'b05f4b2d-a7e3-45e0-b3d0-2458117be185',
  'externalId': 'Mj33ANCR5B96KA6UtCcNll5WrEt1Sjax',
  'publicationStartDate': '2017-06-22',
  'publicationEndDate': '2017-12-26',
  'externalUrl': null,
  'applicationUrl': null,
  'registrationDate': '2017-06-22',
  'cancellationDate': null,
  'cancellationReason': null,
  'title': 'Reinigungskraft m/w',
  'description': 'Wir sind die "meine ALLTAGSHELFER" und suchen zur Ergänzung per sofort eine/n\nReinigungsmitarbeiterin/-mitarbeiter 10 - 50%\n\nSie reinigen ausschliesslich in Privathaushalten und sind sich selbständiges, exaktes Arbeiten gewohnt. Sie\nsind kundenorientiert und schätzen einen loyalen, freundlichen Umgang mit unseren Kunden.\n\nAnforderungen:\n- Erfahrung in der Reinigung von Vorteil\n- Führerschein Kat. B mit eigenem Auto\n- gute Deutschkenntnisse in Wort und Schrift\n- gepflegtes Erscheinungsbild\n\nFür diesen Aufgabenbereich sind Sie idealerweise eine Frau ab 40 Jahre.\n\nWir freuen uns auf Ihre komplette Bewerbung.\nE-mail: meinealltagshelfer@bluewin.ch',
  'workingTimePercentageMin': 50,
  'workingTimePercentageMax': 10,
  'startDate': '2017-06-22',
  'endDate': null,
  'startsImmediately': true,
  'permanent': true,
  'fingerPrint': '531718bd5fb01f9e2872a13a58bc5f8b7b6f97e75123b62405db3ae011446fa10c5998e754d769f2',
  'numberOfJobs': 1,
  'jobSharing': null,
  'suitableForDisabled': false,
  'locality': {
    'text': 'Port',
    'zipCode': '2562',
    'communalCode': '745',
    'cantonCode': 'BE',
    'regionCode': 'BE08',
    'countryCode': 'CH'
  },
  'paymentMin': null,
  'paymentMax': null,
  'currencyCode': 'CHF',
  'ageMin': null,
  'ageMax': null,
  'ageRestrictionReason': null,
  'gender': 'MALE',
  'hasPersonalVehicle': false,
  'drivingLicenseLevel': 'A1',
  'companyName': 'Blitz-Blank GmbH',
  'companyAddressLine1': 'Putzstrasse 3',
  'companyAddressLine2': null,
  'companyZipCode': '3212',
  'companyCity': 'Gurmels',
  'companyCountryCode': 'CH',
  'companyPostboxNumber': null,
  'companyPostboxZipCode': null,
  'companyPostboxCity': null,
  'companyPhone': null,
  'companyEmail': 'xxxx@xxxxxxx.ch',
  'companyWebsite': null,
  'contactTitle': 'Herr',
  'contactFirstName': 'Hans',
  'contactLastName': 'Meiser',
  'contactPhone': '079 999 99 99',
  'contactEmail': null,
  'professions': [{
    'code': '80101',
    'qualificationLevel': null,
    'relation': null,
    'experienceInYears': 10,
    'educationLevel': null
  }],
  'languages': [{
    'code': 'DE',
    'spokenLevel': 'NONE',
    'writtenLevel': 'NONE',
    'isMothertongue': true,
    'isLanguageStayRequired': true
  }]
}, {
  'createdBy': 'system',
  'createdDate': '2017-06-26T06:16:44.465Z',
  'lastModifiedBy': 'system',
  'lastModifiedDate': '2017-06-26T06:16:44.465Z',
  'id': 'a772d6ad-dc68-4150-90c9-4e289cd5ec12',
  'externalId': '1M24HIRGPwggYsBGvGGcwrsd7KlZmbH8',
  'publicationStartDate': '2017-06-22',
  'publicationEndDate': '2017-12-26',
  'externalUrl': 'http://www.externer-stellenvermittler.ch/talent',
  'applicationUrl': null,
  'registrationDate': '2017-06-22',
  'cancellationDate': null,
  'cancellationReason': null,
  'title': 'Software-Entwickler',
  'description': '- 2 Software-Entwickler\n- Stellenantritt per sofort, unbefristet, 100%\n- Aufgaben: Spannende Entwicklungsprojekte realisieren, Weiterentwicklung von Projekten, Durchführung von\nanspruchsvollen Kundenprojekten, Aufgaben im gesamten Entwicklungsprozess\n- Anforderungen: Hochschulabschluss (FH, ETH, Uni) in Informatik, Erfahrung im Bereich Java, Ruby on Rails\noder Python, kennen moderne Entwicklungsprozesse, belastbar, engagiert, kreativ',
  'workingTimePercentageMin': 100,
  'workingTimePercentageMax': 100,
  'startDate': '2017-06-22',
  'endDate': null,
  'startsImmediately': true,
  'permanent': true,
  'fingerPrint': 'b863e2e50f0908a01bfac745bdc9731aee2a5c7367f57d450ceed26750395ab6721503afef3b0b50',
  'numberOfJobs': 1,
  'jobSharing': null,
  'suitableForDisabled': false,
  'locality': {
    'text': 'Chur',
    'zipCode': '7000',
    'communalCode': '3901',
    'cantonCode': 'GR',
    'regionCode': 'GR01',
    'countryCode': 'CH'
  },
  'paymentMin': null,
  'paymentMax': null,
  'currencyCode': 'CHF',
  'ageMin': 25,
  'ageMax': 50,
  'ageRestrictionReason': null,
  'gender': 'FEMALE',
  'hasPersonalVehicle': false,
  'drivingLicenseLevel': null,
  'companyName': 'Max Power IT',
  'companyAddressLine1': 'Putzstrasse 3',
  'companyAddressLine2': null,
  'companyZipCode': '7000',
  'companyCity': 'Chur',
  'companyCountryCode': 'CH',
  'companyPostboxNumber': null,
  'companyPostboxZipCode': null,
  'companyPostboxCity': null,
  'companyPhone': null,
  'companyEmail': 'xxxx@xxxxxxx.ch',
  'companyWebsite': null,
  'contactTitle': 'Herr',
  'contactFirstName': 'Hans',
  'contactLastName': 'Meiser',
  'contactPhone': '079 999 99 99',
  'contactEmail': 'xxxx@xxxxxxx.ch',
  'professions': [{
    'code': '69259',
    'qualificationLevel': null,
    'relation': null,
    'experienceInYears': 1,
    'educationLevel': null
  }],
  'languages': [{
    'code': 'DE',
    'spokenLevel': 'GOOD',
    'writtenLevel': 'VERY_GOOD',
    'isMothertongue': true,
    'isLanguageStayRequired': true
  }]
}, {
  'createdBy': 'system',
  'createdDate': '2017-06-26T06:11:25.306Z',
  'lastModifiedBy': 'system',
  'lastModifiedDate': '2017-06-26T06:11:25.306Z',
  'id': 'e99848a8-1c61-4cce-82f7-dcd3c0a9cbca',
  'externalId': 'lzyfZiW3gHYjN5DiqIjdIZunVGSW3s8Z',
  'publicationStartDate': '2017-06-22',
  'publicationEndDate': '2017-12-26',
  'externalUrl': 'http://www.externer-stellenvermittler.ch/talent',
  'applicationUrl': null,
  'registrationDate': '2017-06-22',
  'cancellationDate': null,
  'cancellationReason': null,
  'title': 'Software-Entwickler',
  'description': '- 2 Software-Entwickler\n- Stellenantritt per sofort, unbefristet, 100%\n- Aufgaben: Spannende Entwicklungsprojekte realisieren, Weiterentwicklung von Projekten, Durchführung von\nanspruchsvollen Kundenprojekten, Aufgaben im gesamten Entwicklungsprozess\n- Anforderungen: Hochschulabschluss (FH, ETH, Uni) in Informatik, Erfahrung im Bereich Java, Ruby on Rails\noder Python, kennen moderne Entwicklungsprozesse, belastbar, engagiert, kreativ',
  'workingTimePercentageMin': 100,
  'workingTimePercentageMax': 100,
  'startDate': '2017-06-22',
  'endDate': null,
  'startsImmediately': true,
  'permanent': true,
  'fingerPrint': 'b863e2e50f0908a01bfac745bdc9731aee2a5c7367f57d450ceed26750395ab6721503afef3b0b50',
  'numberOfJobs': 1,
  'jobSharing': null,
  'suitableForDisabled': false,
  'locality': {
    'text': 'Chur',
    'zipCode': '7000',
    'communalCode': '3901',
    'cantonCode': 'GR',
    'regionCode': 'GR01',
    'countryCode': 'CH'
  },
  'paymentMin': null,
  'paymentMax': null,
  'currencyCode': 'CHF',
  'ageMin': 25,
  'ageMax': 50,
  'ageRestrictionReason': null,
  'gender': 'FEMALE',
  'hasPersonalVehicle': false,
  'drivingLicenseLevel': null,
  'companyName': 'Max Power IT',
  'companyAddressLine1': 'Putzstrasse 3',
  'companyAddressLine2': null,
  'companyZipCode': '7000',
  'companyCity': 'Chur',
  'companyCountryCode': 'CH',
  'companyPostboxNumber': null,
  'companyPostboxZipCode': null,
  'companyPostboxCity': null,
  'companyPhone': null,
  'companyEmail': 'xxxx@xxxxxxx.ch',
  'companyWebsite': null,
  'contactTitle': 'Herr',
  'contactFirstName': 'Hans',
  'contactLastName': 'Meiser',
  'contactPhone': '079 999 99 99',
  'contactEmail': 'xxxx@xxxxxxx.ch',
  'professions': [{
    'code': '69259',
    'qualificationLevel': null,
    'relation': null,
    'experienceInYears': 1,
    'educationLevel': null
  }],
  'languages': [{
    'code': 'DE',
    'spokenLevel': 'GOOD',
    'writtenLevel': 'VERY_GOOD',
    'isMothertongue': true,
    'isLanguageStayRequired': true
  }]
}, {
  'createdBy': 'system',
  'createdDate': '2017-06-26T06:16:44.855Z',
  'lastModifiedBy': 'system',
  'lastModifiedDate': '2017-06-26T06:16:44.855Z',
  'id': 'b1e4ac38-4b3a-4f0a-bc4b-15e09ab2a497',
  'externalId': '9q1xd1oI4QkyFSGGf4MD23DCj7YxyGOs',
  'publicationStartDate': '2017-06-22',
  'publicationEndDate': '2017-12-26',
  'externalUrl': null,
  'applicationUrl': null,
  'registrationDate': '2017-06-22',
  'cancellationDate': null,
  'cancellationReason': null,
  'title': 'Reinigungskraft m/w',
  'description': 'Wir sind die "meine ALLTAGSHELFER" und suchen zur Ergänzung per sofort eine/n\nReinigungsmitarbeiterin/-mitarbeiter 10 - 50%\n\nSie reinigen ausschliesslich in Privathaushalten und sind sich selbständiges, exaktes Arbeiten gewohnt. Sie\nsind kundenorientiert und schätzen einen loyalen, freundlichen Umgang mit unseren Kunden.\n\nAnforderungen:\n- Erfahrung in der Reinigung von Vorteil\n- Führerschein Kat. B mit eigenem Auto\n- gute Deutschkenntnisse in Wort und Schrift\n- gepflegtes Erscheinungsbild\n\nFür diesen Aufgabenbereich sind Sie idealerweise eine Frau ab 40 Jahre.\n\nWir freuen uns auf Ihre komplette Bewerbung.\nE-mail: meinealltagshelfer@bluewin.ch',
  'workingTimePercentageMin': 50,
  'workingTimePercentageMax': 10,
  'startDate': '2017-06-22',
  'endDate': null,
  'startsImmediately': true,
  'permanent': true,
  'fingerPrint': '531718bd5fb01f9e2872a13a58bc5f8b7b6f97e75123b62405db3ae011446fa10c5998e754d769f2',
  'numberOfJobs': 1,
  'jobSharing': null,
  'suitableForDisabled': false,
  'locality': {
    'text': 'Port',
    'zipCode': '2562',
    'communalCode': '745',
    'cantonCode': 'BE',
    'regionCode': 'BE08',
    'countryCode': 'CH'
  },
  'paymentMin': null,
  'paymentMax': null,
  'currencyCode': 'CHF',
  'ageMin': null,
  'ageMax': null,
  'ageRestrictionReason': null,
  'gender': 'MALE',
  'hasPersonalVehicle': false,
  'drivingLicenseLevel': 'A1',
  'companyName': 'Blitz-Blank GmbH',
  'companyAddressLine1': 'Putzstrasse 3',
  'companyAddressLine2': null,
  'companyZipCode': '3212',
  'companyCity': 'Gurmels',
  'companyCountryCode': 'CH',
  'companyPostboxNumber': null,
  'companyPostboxZipCode': null,
  'companyPostboxCity': null,
  'companyPhone': null,
  'companyEmail': 'xxxx@xxxxxxx.ch',
  'companyWebsite': null,
  'contactTitle': 'Herr',
  'contactFirstName': 'Hans',
  'contactLastName': 'Meiser',
  'contactPhone': '079 999 99 99',
  'contactEmail': null,
  'professions': [{
    'code': '80101',
    'qualificationLevel': null,
    'relation': null,
    'experienceInYears': 10,
    'educationLevel': null
  }],
  'languages': [{
    'code': 'DE',
    'spokenLevel': 'NONE',
    'writtenLevel': 'NONE',
    'isMothertongue': true,
    'isLanguageStayRequired': true
  }]
}, {
  'createdBy': 'admin',
  'createdDate': '2017-06-26T06:58:40.295Z',
  'lastModifiedBy': 'admin',
  'lastModifiedDate': '2017-06-26T06:58:40.295Z',
  'id': 'a2c2b6dc-0cbd-40a0-b51d-6b65b16d32d1',
  'externalId': '00000679247',
  'publicationStartDate': '2017-06-22',
  'publicationEndDate': '2017-09-22',
  'externalUrl': null,
  'applicationUrl': null,
  'registrationDate': '2017-06-22',
  'cancellationDate': null,
  'cancellationReason': null,
  'title': 'Reinigungskraft m/w',
  'description': 'Wir sind die "meine ALLTAGSHELFER" und suchen zur Ergänzung per sofort eine/n\nReinigungsmitarbeiterin/-mitarbeiter 10 - 50%\n\nSie reinigen ausschliesslich in Privathaushalten und sind sich selbständiges, exaktes Arbeiten gewohnt. Sie\nsind kundenorientiert und schätzen einen loyalen, freundlichen Umgang mit unseren Kunden.\n\nAnforderungen:\n- Erfahrung in der Reinigung von Vorteil\n- Führerschein Kat. B mit eigenem Auto\n- gute Deutschkenntnisse in Wort und Schrift\n- gepflegtes Erscheinungsbild\n\nFür diesen Aufgabenbereich sind Sie idealerweise eine Frau ab 40 Jahre.\n\nWir freuen uns auf Ihre komplette Bewerbung.\nE-mail: meinealltagshelfer@bluewin.ch',
  'workingTimePercentageMin': 50,
  'workingTimePercentageMax': 10,
  'startDate': '2017-06-22',
  'endDate': '2017-06-22',
  'startsImmediately': true,
  'permanent': true,
  'fingerPrint': '531718bd5fb01f9e2872a13a58bc5f8b7b6f97e75123b62405db3ae011446fa10c5998e754d769f2',
  'numberOfJobs': 1,
  'jobSharing': null,
  'suitableForDisabled': false,
  'locality': {
    'text': 'Port',
    'zipCode': '2562',
    'communalCode': '745',
    'cantonCode': 'BE',
    'regionCode': 'BE08',
    'countryCode': 'CH'
  },
  'paymentMin': null,
  'paymentMax': null,
  'currencyCode': 'CHF',
  'ageMin': null,
  'ageMax': null,
  'ageRestrictionReason': null,
  'gender': 'MALE',
  'hasPersonalVehicle': false,
  'drivingLicenseLevel': 'A1',
  'companyName': 'Blitz-Blank GmbH',
  'companyAddressLine1': 'Putzstrasse 3',
  'companyAddressLine2': null,
  'companyZipCode': '3212',
  'companyCity': 'Gurmels',
  'companyCountryCode': 'CH',
  'companyPostboxNumber': null,
  'companyPostboxZipCode': null,
  'companyPostboxCity': null,
  'companyPhone': null,
  'companyEmail': 'xxxx@xxxxxxx.ch',
  'companyWebsite': null,
  'contactTitle': 'Herr',
  'contactFirstName': 'Hans',
  'contactLastName': 'Meiser',
  'contactPhone': '079 999 99 99',
  'contactEmail': null,
  'professions': [{
    'code': '80101',
    'qualificationLevel': null,
    'relation': null,
    'experienceInYears': 10,
    'educationLevel': null
  }],
  'languages': [{
    'code': 'DE',
    'spokenLevel': 'NONE',
    'writtenLevel': 'NONE',
    'isMothertongue': true,
    'isLanguageStayRequired': true
  }]
}]

@Injectable()
export class JobService {

  constructor() {
  }

  search(term: string): Observable<Job[]> {
    return Observable.of(jobs);
  }
}
